# Generated by Django 4.1.1 on 2022-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='id',
            field=models.CharField(default='s_gH0H0tAxIi-w', max_length=10, primary_key=True, serialize=False, verbose_name='Unique ID of lost item'),
        ),
    ]
