# Generated by Django 4.1.1 on 2022-10-03 17:31

from django.db import migrations, models
import found.models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_alter_found_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='foundDate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date when item was lost'),
        ),
        migrations.AlterField(
            model_name='found',
            name='contactEmail',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Email of finder'),
        ),
        migrations.AlterField(
            model_name='found',
            name='contactPhone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Phone number of finder'),
        ),
        migrations.AlterField(
            model_name='found',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Short description of found item'),
        ),
        migrations.AlterField(
            model_name='found',
            name='id',
            field=models.CharField(default=found.models.newid, max_length=10, primary_key=True, serialize=False, verbose_name='Unique ID of lost item'),
        ),
        migrations.AlterField(
            model_name='found',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Image of founded item'),
        ),
        migrations.AlterField(
            model_name='found',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='location where item was found'),
        ),
    ]
