# Generated by Django 4.1.1 on 2022-10-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('found', '0003_found_founddate_alter_found_contactemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag'),
        ),
    ]
