# Generated by Django 4.1.3 on 2022-11-09 07:58

from django.db import migrations, models
import found.models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_id'),
        ('found', '0005_remove_found_tag_found_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='id',
            field=models.CharField(default=found.models.newid, max_length=16, primary_key=True, serialize=False, verbose_name='Unique ID of lost item'),
        ),
        migrations.AlterField(
            model_name='found',
            name='tag',
            field=models.ManyToManyField(related_name='found', to='tag.tag'),
        ),
    ]
