# Generated by Django 4.1.1 on 2022-10-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Unique ID of tag')),
                ('name', models.CharField(max_length=32, verbose_name='Tag name')),
                ('img', models.CharField(max_length=300, verbose_name='tag image')),
            ],
        ),
    ]
