# Generated by Django 4.1.3 on 2022-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='isCategory',
            field=models.BooleanField(default=False, verbose_name='Show this tag in categories'),
        ),
    ]
