# Generated by Django 4.1.1 on 2022-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.CharField(default='KTCtI6CrirN8Gg', max_length=10, primary_key=True, serialize=False, verbose_name='Unique ID of lost item')),
                ('user_id', models.CharField(max_length=20, verbose_name='User uid')),
                ('user_name', models.CharField(max_length=100, verbose_name='User name')),
                ('title', models.CharField(max_length=50, verbose_name='Title of Lost Item')),
                ('description', models.CharField(max_length=300, verbose_name='Short Description of Lost Item')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Post Created At')),
                ('location', models.CharField(max_length=100, verbose_name='location where item was lost')),
                ('lostDate', models.DateTimeField(verbose_name='Date when item was lost')),
                ('contactEmail', models.EmailField(max_length=50, verbose_name='Email of owner')),
                ('contactPhone', models.CharField(max_length=10, verbose_name='Phone number of owner')),
                ('image', models.CharField(max_length=300, verbose_name='Image of lost item')),
                ('found', models.BooleanField(default=False, verbose_name='Item found or not')),
            ],
        ),
    ]
