# Generated by Django 4.1.1 on 2022-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='contactEmail',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True, verbose_name='Email of owner'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='contactPhone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Phone number of owner'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Short Description of Lost Item'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='id',
            field=models.CharField(default='7AlqfNu259ccAg', max_length=10, primary_key=True, serialize=False, verbose_name='Unique ID of lost item'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Image of lost item'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='location where item was lost'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lostDate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date when item was lost'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Title of Lost Item'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='User uid'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='User name'),
        ),
    ]
