# Generated by Django 4.1.1 on 2022-10-03 17:31

from django.db import migrations, models
import lost.models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_alter_lost_contactemail_alter_lost_contactphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='id',
            field=models.CharField(default=lost.models.newid, max_length=10, primary_key=True, serialize=False, verbose_name='Unique ID of lost item'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Title of Lost Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost',
            name='user_id',
            field=models.CharField(default=None, max_length=20, verbose_name='User uid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost',
            name='user_name',
            field=models.CharField(default=None, max_length=100, verbose_name='User name'),
            preserve_default=False,
        ),
    ]
