# Generated by Django 4.1.3 on 2022-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_id'),
        ('lost', '0009_alter_lost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='tag',
            field=models.ManyToManyField(related_name='lost', to='tag.tag'),
        ),
    ]
