# Generated by Django 4.1.1 on 2022-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='User uid')),
                ('user_name', models.CharField(max_length=100, verbose_name='User name')),
                ('comment', models.CharField(max_length=500)),
                ('user_experience', models.CharField(choices=[('1', 'Very Unsatisfied'), ('2', 'Unsatisfied'), ('3', 'Neutral'), ('4', 'Satisfied'), ('5', 'Very Satisfied')], max_length=1)),
            ],
        ),
    ]
